name: Check

on:
  push:
    branches: ["**"]
  workflow_dispatch:
    inputs:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout 
        uses: actions/checkout@v4
        
      - 
        name: Setup Erlang OTP/Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 26.2.1
          elixir-version: 1.16.0-otp-26

      - 
        name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.75.0
      
      - 
        name: Download Dependencies
        run: mix deps.get
      
      - 
        name: Compile
        run: mix compile --all-warnings --warnings-as-errors
      
      - 
        name: Test
        run: mix test
